url: https://li-ce.github.io
baseurl:

# Site settings
title: Liana Cechladze
email: 
description: "Liana Cechladze software developer portfolio website"

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/liacec
  - title: github
    url: https://www.github.com/li-ce

# Postal address (add as many lines as necessary)
address:
  - line: Portugal

# Build settings
markdown: kramdown
permalink: pretty
