url: https://li-ce.github.io
baseurl: /me/

# Site settings
title: LiaCec
email: 
description: "Liana Cechladze software developer portfolio website"


# Team names, titles and social links
people:
- name: Liana Cechladze
  pic: 1
  position: Software Developer
  social:
    - title: linkedin
      url: linkedin.com/in/liacec

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: linkedin.com/in/liacec
  - title: github
    url: github.com/li-ce

# Postal address (add as many lines as necessary)
address:
  - line: Portugal

# Build settings
markdown: kramdown
permalink: pretty
